name: ssh
on:
  workflow_dispatch: # 手动触发
jobs:
  AutoDownloaderProcess:
    runs-on: ubuntu-20.04
    steps:
     # 输出IP
    - name: IP
      run: sudo curl ifconfig.me
      
    - name: Delete workflow runs
      uses: Mattraks/delete-workflow-runs@main
      with:
          retain_days: 2
          keep_minimum_runs: 6
    - name: Start SSH via ngrok
      uses: winkxx/ssh2actions@main
      with:
         mode: ngrok
         

env:
     NGROK_TOKEN: ${{ secrets.NGROK_TOKEN }}
     NGROK_REGION: au
     SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
